---
include:
  - board: sparkfun_pro_micro_rp2040//zmk
    shield: sofle_left
  - board: sparkfun_pro_micro_rp2040//zmk
    shield: sofle_right
  - board: nice_nano@2//zmk
    shield: sofle_left
    snippet: mcuboot
  - board: nice_nano@2//zmk
    shield: sofle_right
    snippet: mcuboot
  - board: nice_nano@2//zmk
    shield: settings_reset
  - board: xiao_ble//zmk
    shield: sofle_esb_dongle
    snippet: mcuboot
  - board: nice_nano@2//zmk
    shield: sofle_esb_dongle
    snippet: mcuboot
  - board: nice_nano@2//zmk
    shield: sofle_left sofle_esb_left
    snippet: mcuboot
  - board: nice_nano@2//zmk
    shield: sofle_right sofle_esb_right
    snippet: mcuboot
