---
manifest:
  defaults:
      revision: 9ebbeff0a8b69a42f14aec022cdf16c7a107b9e0
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos
  projects:
    - name: zmk
      remote: zmkfirmware
      import: app/west.yml
    - name: mcuboot
      remote: zephyrproject-rtos
      revision: 346f7374ff4467e40b5594658f8ac67a5e9813c9
      path: bootloader/mcuboot
  self:
    path: config
